### ISSUE TITLE
[Feature]: Create a custom YouTubeEmbed Component that wraps the YouTube embed <iframe>

### ISSUE THREAD

**Issue by jimbrig** [noclocks/bastienlaw-remix#18]
for example:

create `app/app/components/YouTubeEmbed.tsx`:

```typescript
import React from 'react';
import '../styles/youtube.css';

interface YouTubeEmbedProps {
    videoId: string;
    title?: string;
    width?: string;
    height?: string;
}

export default function YouTubeEmbed({ videoId, title, width = "560", height = "315" }: YouTubeEmbedProps) {

    const src = `https://www.youtube.com/embed/${videoId}?si=NT6nO5iaFP_2BEKp`;

    return (
        <div className="youtube-container">
            <iframe
                width={width}
                height={height}
                src={src} //{`https://www.youtube.com/embed/${videoId}`}
                title={title}
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerPolicy="strict-origin-when-cross-origin"
                allowFullScreen
            >
            </iframe>
        </div>
    );
}
```

then in `app/app/styles/youtube.css`:

```css
.youtube-container {
    display: flex;
    justify-content: center;
    padding: 20px;
    background-color: #f0f0f0;
}

iframe {
    border: 2px solid #000;
    border-radius: 8px;
}
```

and finally, in `app/app/routes/_index.tsx`:

```typescript
# add imports
import YouTubeEmbed from "../components/YouTubeEmbed";

# add new consts
const YoutubeVideoId = "fdi_z9NLT_w?si=iSeO4L8snTfPbG5H";
const YouTubeVideoTitle = "Villard Bastien"

# add component (lines ~246):
<YouTubeEmbed
  videoId={YoutubeVideoId}
  title={YouTubeVideoTitle}
/>
```
