### ISSUE TITLE
[Feature]: Add GHA for deployment

### ISSUE THREAD

**Issue by jimbrig** [noclocks/bastienlaw-remix#24]
See https://github.com/noclocks/client-bastienlaw/issues/14

```yaml
name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy bastienlaw.com \
        --region useast1 \
        --source .\app\ \
        --allow-unauthenticated
```

**Comment by jimbrig** [comment]
@phoward38 - got the GHA workflow to work (finally). See [the succeeded job](https://github.com/noclocks/bastienlaw-remix/actions/runs/12822005727/job/35754235767) for details.

## Notes

- The deployment and all of the GCP services are now using the separate, dedicated `client-bastienlaw` GCP project (also has its own dedicated billing account)
- Leverages [Direct Workload Identity Federation](https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation) for authenticating with GCP (best practice)
- Merged the `develop` branch into `main` since `main` needed the updated `package.json` fixes you made previously.

## Next Actions

Next we will need to eventually:

- [ ] Migrate the Domain Mappings over to the `client-bastienlaw` cloud run service
- [ ] Will need to re-verify & re-configure the DNS records in hostmonster for this

## GCP Workload Identity & Authentication Setup

1. Create a dedicated *Workload Identity Pool*
2. Create a dedicated *Workload Identity Provider*
3. Create a dedicated service account for github actions: `github-actions-sa`

## IAM Permissions Setup

1. Grant Artifact Registry Writer Role
2. Allow Workload Identity Provider to impersonate the service account
3. Grant Cloud Run Admin Role
4. Grant Service Account User Role on the Compute Engine default Service Account
5. Grant Service Account Token Creator role to the Cloud Run service agent

## GitHub Actions Workflow Configuration

1. Setup Environment Variables (inline, no repository secrets necessary anymore) in the workflow file:

```yaml
env:
  PROJECT_ID: 'client-bastienlaw'
  REGION: 'us-east1'
  SERVICE: 'bastienlaw-website'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/122409892475/locations/global/workloadIdentityPools/github/providers/bastienlaw-remix'
```

2. Configured Authentication Step & Rest of Workflow Configuration Jobs
